// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQOjk-r3KJgTAQ2eA7Og3XF8-x5SPC_FU',
    appId: '1:308182234528:web:661cb59c95a00e6a1ee0c5',
    messagingSenderId: '308182234528',
    projectId: 'app-fatec-lista-tarefas-38602',
    authDomain: 'app-fatec-lista-tarefas-38602.firebaseapp.com',
    storageBucket: 'app-fatec-lista-tarefas-38602.appspot.com',
    measurementId: 'G-D1HVWD1GYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdu3_qdKraH_8Ci4SN0cUrYXj64hh1xDQ',
    appId: '1:308182234528:android:b0df8953f2db6c741ee0c5',
    messagingSenderId: '308182234528',
    projectId: 'app-fatec-lista-tarefas-38602',
    storageBucket: 'app-fatec-lista-tarefas-38602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIuBBFefGAdmYADM_ikRqCkQoF-X0ckg',
    appId: '1:308182234528:ios:8ab7930b78164e1c1ee0c5',
    messagingSenderId: '308182234528',
    projectId: 'app-fatec-lista-tarefas-38602',
    storageBucket: 'app-fatec-lista-tarefas-38602.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}